version: '3.3'

services:
  docker:
    build:
      context: .
      dockerfile: Dockerfile

    # Allow container to access host's pid namespace.
    # Normally, processes inside a container have their
    # own namespace that is inaccessible to the host
    # when running tasks such as `ps`. `pid: host` sets
    # container pid's to pids allocated by the host
    # system's process management.
    # pid: host

    volumes:
      # - type: volume
      #   source: /var/run/docker.sock
      #   target: /var/run/docker.sock
      #   read_only: false
      #   uid: 1000
      #   gid: 1000

      - /var/run/docker.sock:/var/run/docker.sock

      # - type: volume
      #   source: docker_sock
      #   target: /var/run/docker.sock
      #   # target: /var/run
      #   read_only: false
      #   uid: 1000
      #   gid: 1000


# volumes:
#   docker_sock:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /var/run/docker.sock
#       # device: /var/run

