version: '3.3'

# Resources on running gitlab in docker:
# https://developer.ibm.com/code/2017/07/13/step-step-guide-running-gitlab-ce-docker/
# https://docs.gitlab.com/omnibus/docker/README.html
#
# Docker Hub Repo:
# https://hub.docker.com/r/gitlab/gitlab-ce/
services:
  gitlab:
    image: 127.0.0.1:5000/johnellis1392/gitlab
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1

    # environment:
      # Additional configuration for stuff
      # GITLAB_OMNIBUS_CONFIG: |
      #   external_url 'https://gitlab.celestia.com'

    ports:
      # HTTP
      - published: 8080
        target: 80
        protocol: tcp

        # Docker port mode options:
        # * host: Bind to host port
        # * ingress: Create virtual ingress port for swarm load balancing
        mode: host

      # HTTPS
      - published: 8443
        target: 443
        protocol: tcp
        mode: host

      # SSH
      - published: 8022
        target: 22
        protocol: tcp
        mode: host

      # Unicorn
      - published: 8081
        target: 8080
        protocol: tcp
        mode: host


    volumes:
      # Configs
      - type: volume
        source: gitlab_configs
        target: /etc/gitlab
        read_only: false
        volume:
          nocopy: true

      # Logs
      - type: volume
        source: gitlab_logs
        target: /var/log/gitlab
        read_only: false
        volume:
          nocopy: true

      # Data
      - type: volume
        source: gitlab_data
        target: /var/opt/gitlab
        read_only: false
        volume:
          nocopy: true

    # NOTE: This config file should be passed in through
    # the /etc/gitlab volume mount. Do one or the other;
    # mount a config dir or pass in this config.
    # configs:
    #   - source: gitlab_rb
    #     target: /etc/gitlab/gitlab.rb
    #     uid: '1000'
    #     gid: '1000'
    #     mode: 0440


    # secrets:
    #   - source: gitlab_https_pem
    #     target: ...
    #     uid: '1000'
    #     gid: '1000'
    #     mode: 0440

    #   - source: gitlab_https_key
    #     target: ...
    #     uid: '1000'
    #     gid: '1000'
    #     mode: 0440


# NOTE: Consider mounting these volumes to a directory like
# /srv/gitlab/
volumes:
  gitlab_configs:
    driver: local

  gitlab_logs:
    driver: local

  gitlab_data:
    driver: local


secrets:
  gitlab_https_pem:
    file: ./certs/https.pem
  gitlab_https_key:
    file: ./certs/https.key


# configs:
#   gitlab_rb:
#     file: ./gitlab.rb


