version: '3.3'

services:
  app:
    build: .
    environment:
      DISPLAY: unix$DISPLAY

    # devices:
    #  - /dev/dri

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

    entrypoint:
      - glxgears

