version: '3.3'

services:
  app:
    build: .
    environment:
      # DISPLAY: unix$DISPLAY
      # DISPLAY: $DISPLAY
      DISPLAY: "192.168.59.3:0"
    # privileged: true

    # devices:
    #   - /dev/dri

      # volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix

    entrypoint:
      - glxgears

